### ISSUE TITLE
query-bean API fails without Default DB

### ISSUE THREAD

**Issue by turbospaces** [ebean-orm/ebean-querybean#67] opened 2019-09-20 10:28 UTC
When Ebean server is initialized without Default DB, meaning that EbeanServer is explicitly passed as reference to DAO objects, any attempt to use Query beans in a way

`
QPlayer q = new QPlayer( ebean ).usingTransaction( tx );
` 
fails with error, even though Ebean is passed into constructor
`
Caused by: io.ebean.datasource.DataSourceConfigurationException: DataSource user is null?
	at io.ebean.datasource.pool.ConnectionPool.<init>(ConnectionPool.java:227)
	at io.ebean.datasource.core.Factory.createPool(Factory.java:15)
	at io.ebeaninternal.server.core.DefaultContainer.getDataSourceFromConfig(DefaultContainer.java:273)
	at io.ebeaninternal.server.core.DefaultContainer.setDataSource(DefaultContainer.java:217)
	at io.ebeaninternal.server.core.DefaultContainer.createServer(DefaultContainer.java:103)
	at io.ebeaninternal.server.core.DefaultContainer.createServer(DefaultContainer.java:69)
	at io.ebeaninternal.server.core.DefaultContainer.createServer(DefaultContainer.java:35)
	at io.ebean.EbeanServerFactory.create(EbeanServerFactory.java:58)
	at io.ebean.Ebean$ServerManager.getWithCreate(Ebean.java:126)
	at io.ebean.Ebean$ServerManager.<init>(Ebean.java:75)
	... 37 more
`
It looks like there default constructor is being called during class loading/initialization

`
  public TQRootBean(Class<T> beanType) {
    this(beanType, DB.getDefault());
  }
`

Bug is always reproducible, on any generated Query bean

**Comment by rbygrave** [comment] 2019-09-24 00:20
> It looks like there default constructor is being called during class loading/initialization

Can you get more of the stack

> io.ebean.Ebean$ServerManager.<init>(Ebean.java:75) ... 37 more

We want more of the stack to identify where this is being called from

**Comment by rbygrave** [comment] 2019-09-24 10:02
I can't reproduce.  

What version of Ebean are you using?  What version of ebean-querybean?

**Comment by rbygrave** [comment] 2019-10-05 08:59
Closing - not reproduced, no further information.

**Closed by rbygrave** 2019-10-05 08:59 UTC
